apiVersion: v1
kind: Service
metadata:
  name: chatbot-nalantis-lb
  labels:
    app: chatbot-nalantis-lb
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: chatbot-nalantis
  type: LoadBalancer